### ISSUE TITLE
Questions about your component usage

### ISSUE THREAD

**Issue by scramatte** [superhussain/vue-joystick-component#1]
Hello,

I'm trying your joystick component. I've got some doubt about few things.
Does it possible to maintain the stick inside the main circle? 
How can set transparency on stick and background?

Regards

**Comment by superhussain** [comment]
hi!

> Does it possible to maintain the stick inside the main circle?

i have not built the component to allow for that, but can definitely see its use case. contributions are welcome!

> How can set transparency on stick and background?

the component uses CSS `background` for `stickColor` and `baseColor`, so you can supply any color value supported by CSS `background`. here's an example of transparent backgrounds:

![image](https://user-images.githubusercontent.com/5639253/227971218-2b2a50e4-aaed-46b3-99a1-8467f7e46798.png)

![image](https://user-images.githubusercontent.com/5639253/227971246-051c47a0-ebe1-4441-bc7c-fa7a81064c69.png)

you can use the histoire playground to test out different prop values:
https://superhussain.github.io/vue-joystick-component/#/story/stories-joystick-story-vue?variantId=_default
